In [2]:
import numpy as np
print(np.__version__)

1.21.5


In [9]:
from numpy import zeros,empty,ones
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
print(zeros([2,2]))

[[0. 0.]
 [0. 0.]]


In [15]:
print(empty([4,2]))

[[0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 8.08291397e-321]
 [1.42413554e-306 1.78019082e-306]]


In [16]:
print(ones([2,2]))

[[1. 1.]
 [1. 1.]]


In [17]:
print(np.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
